"use client";

import { useMemo, useState } from "react";
import Highlight, { defaultProps } from "prism-react-renderer";
import nightOwlTheme from "prism-react-renderer/themes/nightOwl";

interface IndicatorConfig {
  trendLength: number;
  volatilityLength: number;
  signalSmoothing: number;
  volatilityMultiplier: number;
  paintBars: boolean;
}

const defaultConfig: IndicatorConfig = {
  trendLength: 34,
  volatilityLength: 21,
  signalSmoothing: 5,
  volatilityMultiplier: 1.6,
  paintBars: true
};

const numberField = (
  label: string,
  value: number,
  setValue: (v: number) => void,
  min: number,
  max: number,
  step = 1
) => (
  <label
    key={label}
    style={{
      display: "flex",
      flexDirection: "column",
      gap: "0.25rem",
      fontSize: "0.95rem"
    }}
  >
    {label}
    <input
      type="range"
      min={min}
      max={max}
      step={step}
      value={value}
      onChange={(event) => setValue(Number(event.target.value))}
    />
    <span
      style={{
        fontVariantNumeric: "tabular-nums",
        fontSize: "0.85rem",
        color: "#cbd5f5"
      }}
    >
      {value}
    </span>
  </label>
);

export default function HomePage(): JSX.Element {
  const [config, setConfig] = useState<IndicatorConfig>(defaultConfig);
  const [copied, setCopied] = useState(false);

  const pascalCode = useMemo(() => {
    const paintBarsBlock = config.paintBars
      ? `
if Signal crosses above 0 then
begin
    PlotPaintBar(1, High, Low, Close, RGB(34, 197, 94));
    Alert('ATS: compra - fechamento ' + NumToStr(Close, 2));
end;

if Signal crosses below 0 then
begin
    PlotPaintBar(2, High, Low, Close, RGB(239, 68, 68));
    Alert('ATS: venda - fechamento ' + NumToStr(Close, 2));
end;`
      : "";

    return `// Indicator generated by agentic-94c7ec03
// Adaptive Trend Shield for ProfitChart Pro

Inputs:
    TrendLength(${config.trendLength}),
    VolatilityLength(${config.volatilityLength}),
    SignalSmoothing(${config.signalSmoothing}),
    VolatilityMultiplier(${config.volatilityMultiplier.toFixed(2)});

Vars:
    TrendEMA(0),
    VolatilityATR(0),
    Signal(0),
    UpperBand(0),
    LowerBand(0),
    TrendBias(0);

TrendEMA := XAverage(Close, TrendLength);
VolatilityATR := AvgTrueRange(VolatilityLength);
UpperBand := TrendEMA + (VolatilityATR * VolatilityMultiplier);
LowerBand := TrendEMA - (VolatilityATR * VolatilityMultiplier);
TrendBias := Close - TrendEMA;
Signal := XAverage(TrendBias, SignalSmoothing);

Plot1(TrendEMA, 'TrendEMA');
Plot2(UpperBand, 'UpperBand');
Plot3(LowerBand, 'LowerBand');
Plot4(Signal, 'Signal');
Plot5(TrendBias, 'Bias');

if Signal > 0 then
    SetPlotColor(5, RGB(34, 197, 94))
else if Signal < 0 then
    SetPlotColor(5, RGB(239, 68, 68))
else
    SetPlotColor(5, RGB(148, 163, 184));${paintBarsBlock}

SetPlotWidth(1, 2);
SetPlotWidth(2, 1);
SetPlotWidth(3, 1);

Commentary(0, 'Adaptive Trend Shield');
Commentary(1, 'Tendencia: ' + NumToStr(TrendEMA, 2));
Commentary(2, 'Vies: ' + NumToStr(TrendBias, 2));
Commentary(3, 'Sinal: ' + NumToStr(Signal, 2));
`;
  }, [config]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(pascalCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error("clipboard", error);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([pascalCode], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "adaptive_trend_shield.pas";
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main
      style={{
        maxWidth: "960px",
        margin: "0 auto",
        display: "flex",
        flexDirection: "column",
        gap: "2.5rem"
      }}
    >
      <header
        style={{
          display: "flex",
          flexDirection: "column",
          gap: "0.75rem"
        }}
      >
        <h1 style={{ fontSize: "2.75rem", fontWeight: 700 }}>
          Adaptive Trend Shield
        </h1>
        <p style={{ maxWidth: "720px", color: "#cbd5f5", lineHeight: 1.6 }}>
          Gerador de indicador avançado para ProfitChart Pro escrito em Pascal.
          Ajuste os parâmetros para moldar a sensibilidade do detector de
          tendência com bandas dinâmicas baseadas em volatilidade.
        </p>
      </header>

      <section
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
          gap: "1.5rem",
          background: "rgba(15, 23, 42, 0.6)",
          padding: "1.5rem",
          borderRadius: "1rem",
          border: "1px solid rgba(148, 163, 184, 0.2)",
          backdropFilter: "blur(12px)"
        }}
      >
        {numberField(
          "Trend Length",
          config.trendLength,
          (trendLength) => setConfig((prev) => ({ ...prev, trendLength })),
          5,
          120
        )}
        {numberField(
          "Volatility Length",
          config.volatilityLength,
          (volatilityLength) => setConfig((prev) => ({ ...prev, volatilityLength })),
          5,
          60
        )}
        {numberField(
          "Signal Smoothing",
          config.signalSmoothing,
          (signalSmoothing) => setConfig((prev) => ({ ...prev, signalSmoothing })),
          2,
          20
        )}
        {numberField(
          "Volatility Multiplier",
          config.volatilityMultiplier,
          (volatilityMultiplier) =>
            setConfig((prev) => ({ ...prev, volatilityMultiplier })),
          1,
          4,
          0.1
        )}
        <label
          style={{
            display: "flex",
            alignItems: "center",
            gap: "0.75rem",
            fontSize: "0.95rem"
          }}
        >
          <input
            type="checkbox"
            checked={config.paintBars}
            onChange={(event) =>
              setConfig((prev) => ({ ...prev, paintBars: event.target.checked }))
            }
          />
          Pintar candles com alertas
        </label>
      </section>

      <section
        style={{
          background: "rgba(15, 23, 42, 0.6)",
          borderRadius: "1rem",
          border: "1px solid rgba(148, 163, 184, 0.2)",
          overflow: "hidden",
          boxShadow: "0 20px 50px rgba(15, 23, 42, 0.45)"
        }}
      >
        <div
          style={{
            display: "flex",
            gap: "0.75rem",
            padding: "1rem",
            borderBottom: "1px solid rgba(148, 163, 184, 0.15)",
            background: "rgba(30, 41, 59, 0.65)",
            alignItems: "center"
          }}
        >
          <button
            onClick={handleCopy}
            style={{
              background: copied ? "#22c55e" : "#3b82f6",
              border: "none",
              borderRadius: "0.75rem",
              padding: "0.6rem 1.1rem",
              color: "white",
              fontWeight: 600,
              transition: "background 0.2s ease"
            }}
          >
            {copied ? "Copiado" : "Copiar código"}
          </button>
          <button
            onClick={handleDownload}
            style={{
              background: "rgba(59, 130, 246, 0.15)",
              border: "1px solid rgba(59, 130, 246, 0.35)",
              borderRadius: "0.75rem",
              padding: "0.6rem 1.1rem",
              color: "#bfdbfe",
              fontWeight: 600
            }}
          >
            Baixar .pas
          </button>
        </div>
        <Highlight {...defaultProps} theme={nightOwlTheme} code={pascalCode} language="clike">
          {({ className, style, tokens, getLineProps, getTokenProps }) => (
            <pre
              className={className}
              style={{
                ...style,
                margin: 0,
                padding: "1.5rem",
                fontSize: "0.9rem",
                lineHeight: 1.6,
                overflowX: "auto"
              }}
            >
              {tokens.map((line, i) => (
                <div key={i} {...getLineProps({ line })}>
                  {line.map((token, key) => (
                    <span key={key} {...getTokenProps({ token, key })} />
                  ))}
                </div>
              ))}
            </pre>
          )}
        </Highlight>
      </section>

      <section
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
          gap: "1.25rem"
        }}
      >
        <article
          style={{
            background: "rgba(30, 41, 59, 0.55)",
            padding: "1.5rem",
            borderRadius: "1rem",
            border: "1px solid rgba(148, 163, 184, 0.15)",
            lineHeight: 1.6
          }}
        >
          <h2 style={{ fontSize: "1.25rem", marginBottom: "0.75rem" }}>
            Como usar no ProfitChart
          </h2>
          <ol style={{ margin: 0, paddingLeft: "1.25rem" }}>
            <li>Copie ou baixe o arquivo .pas gerado.</li>
            <li>Acesse o ProfitChart Pro e abra o Editor de Indicadores.</li>
            <li>Cole o código em um novo indicador chamado Adaptive Trend Shield.</li>
            <li>Compile e insira no gráfico ajustando os inputs conforme necessário.</li>
          </ol>
        </article>
        <article
          style={{
            background: "rgba(30, 41, 59, 0.55)",
            padding: "1.5rem",
            borderRadius: "1rem",
            border: "1px solid rgba(148, 163, 184, 0.15)",
            lineHeight: 1.6
          }}
        >
          <h2 style={{ fontSize: "1.25rem", marginBottom: "0.75rem" }}>
            Estrutura do indicador
          </h2>
          <ul style={{ margin: 0, paddingLeft: "1.25rem" }}>
            <li>Trend EMA define a direção predominante.</li>
            <li>Bandas ajustadas pela volatilidade delimitam zonas de reversão.</li>
            <li>Sinal suavizado orienta alertas e coloração de candles.</li>
            <li>Comentários exibem valores chave em tempo real.</li>
          </ul>
        </article>
      </section>
    </main>
  );
}
