// Indicator generated by agentic-94c7ec03
// Adaptive Trend Shield for ProfitChart Pro

Inputs:
    TrendLength(34),
    VolatilityLength(21),
    SignalSmoothing(5),
    VolatilityMultiplier(1.60);

Vars:
    TrendEMA(0),
    VolatilityATR(0),
    Signal(0),
    UpperBand(0),
    LowerBand(0),
    TrendBias(0);

TrendEMA := XAverage(Close, TrendLength);
VolatilityATR := AvgTrueRange(VolatilityLength);
UpperBand := TrendEMA + (VolatilityATR * VolatilityMultiplier);
LowerBand := TrendEMA - (VolatilityATR * VolatilityMultiplier);
TrendBias := Close - TrendEMA;
Signal := XAverage(TrendBias, SignalSmoothing);

Plot1(TrendEMA, 'TrendEMA');
Plot2(UpperBand, 'UpperBand');
Plot3(LowerBand, 'LowerBand');
Plot4(Signal, 'Signal');
Plot5(TrendBias, 'Bias');

if Signal > 0 then
    SetPlotColor(5, RGB(34, 197, 94))
else if Signal < 0 then
    SetPlotColor(5, RGB(239, 68, 68))
else
    SetPlotColor(5, RGB(148, 163, 184));

if Signal crosses above 0 then
begin
    PlotPaintBar(1, High, Low, Close, RGB(34, 197, 94));
    Alert('ATS: compra - fechamento ' + NumToStr(Close, 2));
end;

if Signal crosses below 0 then
begin
    PlotPaintBar(2, High, Low, Close, RGB(239, 68, 68));
    Alert('ATS: venda - fechamento ' + NumToStr(Close, 2));
end;

SetPlotWidth(1, 2);
SetPlotWidth(2, 1);
SetPlotWidth(3, 1);

Commentary(0, 'Adaptive Trend Shield');
Commentary(1, 'Tendencia: ' + NumToStr(TrendEMA, 2));
Commentary(2, 'Vies: ' + NumToStr(TrendBias, 2));
Commentary(3, 'Sinal: ' + NumToStr(Signal, 2));
